### PR TITLE
Added proxy support to Frameworkium

### PR DESCRIPTION
**Pull request by BenSmith-CR**
Added proxy support to Frameworkium by creating new system properties for setting a proxy type and proxy address and using these in the browser capabilities.

As this is my first change to Frameworkium I would appreciate comments on the code style and whether it matches what you want as well as checking that this change is correct

### CODE REVIEW

**Comment by jleeh** [comment]
Hey, couple of suggestions on the code.
- Rather than creating an abstract class which extends DriverType, which the browsers extend, simply place 'getProxy()' inside DriverType.
- I'm not too keen on the duplication of the proxy code throughout the drivers. You could extract that code and put it in it's own separate method called 'setProxy' which is in DriverType and is called in the instantiation of the driver. With that, we've got one common method which all browsers support, but if a browser has it's own way of adding proxy, it can be overridden in the browsers class.

Great work though :+1:

**Comment by robertgates55** [comment]
Agree with jonny on the duplication - I think you can do this without touching each of the individual browser etc files (and we can put @Overrides in them if any of them need any extra magic later down the line?)

Also - -DproxyType and -DproxyAddress - not sure, but is there a more standard way to specify these? As an example, if I provide proxyType=system and proxyAddress=10.23.14.2:80, presumably It'll use  the system settings? Is there a single param way that's neater? proxy=10.23.151.23:80 or proxy=auto-detect or proxy=system etc etc? No idea - am just thinking out loud as it doesn't look as self-explanatory as perhaps it could do? What does it default to, if not provided? Auto? Or whatever IE is set to on the box? Is that system?!

**Comment by robertgates55** [comment]
Oh and jonny, branching strategy wise, are we ok to go direct into master with this? I know there was a desire to go via develop...

**Comment by jleeh** [comment]
I've got the fixes for the browser resetting and various smaller things on develop. I didn't want to merge it in to master due to not wanting to crazy on releases. I'll create a pull request after this is completed which will include all the changes and merge it in to master. 

Actually, since we're tagging/releasing, there's not really that much need for develop.. I'll remove it after this work is done.

**Comment by BenSmith-CR** [comment]
Feedback noted, I will close and replace with a version which actions your comments

**Pull request closed without merging**
